main: muriplz.kryeittpplugin.KryeitTPPlugin
version: 3.2.0
name: Telepost
author: muriplz and BlockOG
depend: [AdvancedTeleport]
api-version: 1.16
commands:
  nearestpost:
    description: gets the nearest post location.
  setpost:
    description: sets the nearest post as your home.
  invite:
    aliases:
      invitepost
      inviteplayer
    description: invite a player to your home post.
  homepost:
    description: teleports to your home post.
  v:
    aliases: visit
    description: visits a post.
  namepost:
    description: names the nearest post.
  unnamepost:
    description: unnames a post.
  buildpost:
    description: builds a post.
    aliases: bp
    usage:
      /<command>
      /<command> <y>
      /<command> <x> <z>
      /<command> <x> <y> <z>
  posthelp:
    description: tells info about Telepost commands.
    aliases:
      phelp
      ph
    usage:
      /<command>
      /<command> <another command>