main: muriplz.kryeittpplugin.KryeitTPPlugin
version: 3.6.1
name: Telepost
author: muriplz and BlockOG
depend: [AdvancedTeleport]
api-version: 1.16
commands:
  nearestpost:
    description: gets the nearest post location.
  setpost:
    description: sets the nearest post as your home.
  invite:
    description: invite a player to your home post.
  homepost:
    description: teleports to your home post.
    aliases: h
  v:
    aliases: visit
    description: visits a post.
  namepost:
    description: names the nearest post.
    permission: telepost.namepost
  unnamepost:
    description: unnames a post.
    permission: telepost.unnamepost
  buildpost:
    description: builds a post.
    permission: telepost.buildpost
  posthelp:
    description: tells info about Telepost commands.
  postlist:
    description: shows all the named posts, and lets you teleport by clicking.
    aliases: postslist