main: muriplz.kryeittpplugin.KryeitTPPlugin
version: 2.0.0
name: Kryeit-tpPlugin
commands:
  nearestpost:
    description: nearest post.
  setpost:
    description: sets the nearest post as a home.
  invite:
    description: invite a player to your home post.
  homepost:
    description: goes to your home post.
  v:
    description: visit a post.