main: muriplz.kryeittpplugin.KryeitTPPlugin
version: 2.0.1
name: Kryeit-tpPlugin
author: muriplz
depend: [AdvancedTeleport]
api-version: 1.16
commands:
  nearestpost:
    description: nearest post.
  setpost:
    description: sets the nearest post as a home.
  invite:
    description: invite a player to your home post.
  homepost:
    description: goes to your home post.
  v:
    aliases: visit
    description: visit a post.