main: muriplz.kryeittpplugin.KryeitTPPlugin
version: 3.0.8
name: Telepost
author: muriplz and BlockOG
depend: [AdvancedTeleport]
api-version: 1.16
commands:
  nearestpost:
    description: nearest post.
  setpost:
    description: sets the nearest post as a home.
  invite:
    aliases: invitepost, inviteplayer
    description: invite a player to your home post.
  homepost:
    aliases: hp
    description: goes to your home post.
  v:
    aliases: visit
    description: visits a post.
  namepost:
    description: names the nearest post.
  unnamepost:
    description: unnames a post.
  buildpost:
    aliases: bp
    description: builds a post
    usage:
      /<command>
      /<command> <y>
      /<command> <x> <z>
      /<command> <x> <y> <z>