main: com.kryeit.Telepost
version: 2.1
name: Telepost
description: Posts to keep people connected!
authors: [MuriPlz,MrRedRhino]
softdepend: [GriefDefender,StructureBlockLib]
api-version: 1.18
commands:
  nearestpost:
    description: gets the nearest post location.
  setpost:
    description: sets the nearest post as your homepost.
  invite:
    description: invite a player to your homepost.
  homepost:
    description: teleports to your homepost.
    aliases: h
  visit:
    description: visits a post.
    aliases: v
  namepost:
    description: names the nearest post.
  unnamepost:
    description: unnames a post.
    permission: telepost.unnamepost
  posthelp:
    description: tells info about Telepost commands.
  postlist:
    description: shows all the named posts, and lets you teleport by clicking.
  dumpdb:
    description: Dumps the database
    permission: telepost.dumpdb
  claimposts:
    description: Claims all posts
    permission: telepost.claimposts
  buildposts:
    description: Builds all posts
    permission: telepost.buildposts