main: com.kryeit.Telepost
version: 1.3-DEV4
name: Telepost
description: Posts to keep people connected!
author: MuriPlz
depend: [AdvancedTeleport]
api-version: 1.18
commands:
  nearestpost:
    description: gets the nearest post location.
  setpost:
    description: sets the nearest post as your home.
  invite:
    description: invite a player to your home post.
  homepost:
    description: teleports to your home post.
    aliases: h
  visit:
    aliases: v
    description: visits a post.
  namepost:
    description: names the nearest post.
    permission: telepost.namepost
  unnamepost:
    description: unnames a post.
    permission: telepost.unnamepost
  posthelp:
    description: tells info about Telepost commands.
  postlist:
    description: shows all the named posts, and lets you teleport by clicking.
    aliases: plist